/**
 * Regenerates `src/countries.gen.ts` — the country codes the picker offers.
 *
 * Run: `npm run generate:countries -w console/ui` (needs AWS credentials; the
 * API itself is public, but the CLI still signs the request).
 *
 * Source: `aws route53 list-geo-locations`. CloudFront publishes no list of the
 * countries `CloudFront-Viewer-Country` can carry, and Route 53's geolocation
 * set is the closest machine-readable one AWS offers — both are ISO 3166-1
 * alpha-2. It is *not* a contract that the two sets are identical, which is one
 * more reason nothing validates against this list: it is what the picker offers,
 * never what the app accepts. See the header of the generated file.
 *
 * Only the codes are taken. Route 53's own names are not display quality (it
 * calls US "USA"), so `countryName` in src/countries.ts asks
 * `Intl.DisplayNames` instead — better wording, translated for free, and nothing
 * to maintain here.
 *
 * There is deliberately no `generate:countries:check` in CI, unlike
 * `generate:api:check`: that would need AWS credentials in CI to watch for an
 * event that happens about once a decade (SS in 2011, CW/SX/BQ in 2010, RS/ME
 * in 2006). A stale list is not a blocker either way — the picker takes a code
 * it does not know, and the edge matches it. Refreshing only removes the
 * warning next to it.
 */
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

interface GeoLocationDetails {
  ContinentCode?: string;
  CountryCode?: string;
  CountryName?: string;
  SubdivisionCode?: string;
}

const OUT = join(
  dirname(fileURLToPath(import.meta.url)),
  "..",
  "src",
  "countries.gen.ts",
);

const raw = execFileSync(
  "aws",
  ["route53", "list-geo-locations", "--output", "json"],
  { encoding: "utf8", maxBuffer: 8 * 1024 * 1024 },
);

const { GeoLocationDetailsList: entries } = JSON.parse(raw) as {
  GeoLocationDetailsList: GeoLocationDetails[];
};

const codes = entries
  .filter(
    (entry) =>
      // Continent-level rows carry no country, and a country's subdivisions
      // (US states) repeat its code once per state.
      entry.SubdivisionCode === undefined &&
      // Route 53 uses "*" for its default location, which is not a place.
      // Anything else that is not two letters would fail the rule schema's
      // pattern anyway, so it has no business in the picker.
      /^[A-Z]{2}$/.test(entry.CountryCode ?? ""),
  )
  .map((entry) => entry.CountryCode as string)
  .sort();

const unique = [...new Set(codes)];
if (unique.length < 200) {
  // A partial page or a changed response shape would otherwise silently shrink
  // the picker to a handful of countries.
  throw new Error(
    `refusing to write ${unique.length} countries: expected the full ISO list, so the response looks truncated or its shape changed`,
  );
}

const file = `// Generated by scripts/generate-countries.ts. Do not edit by hand.
//
// The country codes the picker offers, from \`aws route53 list-geo-locations\`.
// Refresh with \`npm run generate:countries -w console/ui\`.
//
// This list is a convenience, never an authority: it is what the picker shows,
// and nothing validates against it. The rule schema checks the *format* of a
// country code and the edge only compares strings, so a code missing from here
// still saves and still matches. A stale list costs a warning next to that
// code, nothing more.
//
// Names are not stored: \`countryName\` in ./countries.ts asks
// \`Intl.DisplayNames\`, so there is nothing to translate or maintain.

export const COUNTRY_CODES = [
${unique.map((code) => `  "${code}",`).join("\n")}
] as const;
`;

writeFileSync(OUT, file, "utf8");
console.log(`wrote ${unique.length} country codes to ${OUT}`);
