import { COUNTRY_CODES } from "./countries.gen";

/**
 * The country picker's data, and the only place in the app that holds a list of
 * countries at all.
 *
 * It is a convenience, never an authority. The rule schema validates a code's
 * *format* and the edge only compares strings, so a code absent from here still
 * saves and still matches — see `shared/redirect-rule.schema.json`. Nothing in
 * this file may be used to reject a value.
 *
 * Codes come from `countries.gen.ts` (Route 53, regenerated by
 * `npm run generate:countries`). Names come from `Intl.DisplayNames`, so there
 * is no list of names to maintain or translate. The continent of each country
 * is the one thing AWS does not give us, so it is the one thing kept by hand
 * below.
 */

export const CONTINENT_NAMES = {
  NA: "North America",
  EU: "Europe",
  AS: "Asia",
  SA: "South America",
  AF: "Africa",
  OC: "Oceania",
  AN: "Antarctica",
} as const;

export type ContinentCode = keyof typeof CONTINENT_NAMES;

/**
 * Display order, and deliberately not alphabetical or geographic: it puts the
 * continents this console's users pick from most first, so the common case
 * needs no scrolling. Reorder freely, nothing depends on it.
 */
export const CONTINENT_ORDER = Object.keys(CONTINENT_NAMES) as ContinentCode[];

/** The group an unrecognised code falls into. Never dropped, only set aside. */
export const OTHER_GROUP = "Other";

/**
 * Which continent each country is shown under.
 *
 * Written as one list per continent rather than one line per country: 250 lines
 * of `"FR": "EU"` are unreviewable, whereas a missing or duplicated code here is
 * something `countries.test.ts` catches against `COUNTRY_CODES`.
 *
 * A handful of placements are conventions rather than facts — Turkey and the
 * Caucasus straddle two continents, Russia spans both, and Cyprus is in Asia by
 * UN geoscheme and in Europe by everything a user expects. These are grouping
 * labels in a picker, not a geopolitical position, and a country can be found by
 * name or code regardless of the heading it sits under.
 */
const CODES_BY_CONTINENT: Record<ContinentCode, readonly string[]> = {
  NA: [
    "AG",
    "AI",
    "AW",
    "BB",
    "BL",
    "BM",
    "BQ",
    "BS",
    "BZ",
    "CA",
    "CR",
    "CU",
    "CW",
    "DM",
    "DO",
    "GD",
    "GL",
    "GP",
    "GT",
    "HN",
    "HT",
    "JM",
    "KN",
    "KY",
    "LC",
    "MF",
    "MQ",
    "MS",
    "MX",
    "NI",
    "PA",
    "PM",
    "PR",
    "SV",
    "SX",
    "TC",
    "TT",
    "US",
    "VC",
    "VG",
    "VI",
  ],
  EU: [
    "AD",
    "AL",
    "AT",
    "AX",
    "BA",
    "BE",
    "BG",
    "BY",
    "CH",
    "CY",
    "CZ",
    "DE",
    "DK",
    "EE",
    "ES",
    "FI",
    "FO",
    "FR",
    "GB",
    "GG",
    "GI",
    "GR",
    "HR",
    "HU",
    "IE",
    "IM",
    "IS",
    "IT",
    "JE",
    "LI",
    "LT",
    "LU",
    "LV",
    "MC",
    "MD",
    "ME",
    "MK",
    "MT",
    "NL",
    "NO",
    "PL",
    "PT",
    "RO",
    "RS",
    "RU",
    "SE",
    "SI",
    "SJ",
    "SK",
    "SM",
    "UA",
    "VA",
    "XK",
  ],
  AS: [
    "AE",
    "AF",
    "AM",
    "AZ",
    "BD",
    "BH",
    "BN",
    "BT",
    "CC",
    "CN",
    "CX",
    "GE",
    "HK",
    "ID",
    "IL",
    "IN",
    "IQ",
    "IR",
    "JO",
    "JP",
    "KG",
    "KH",
    "KP",
    "KR",
    "KW",
    "KZ",
    "LA",
    "LB",
    "LK",
    "MM",
    "MN",
    "MO",
    "MV",
    "MY",
    "NP",
    "OM",
    "PH",
    "PK",
    "PS",
    "QA",
    "SA",
    "SG",
    "SY",
    "TH",
    "TJ",
    "TL",
    "TM",
    "TR",
    "TW",
    "UZ",
    "VN",
    "YE",
  ],
  SA: [
    "AR",
    "BO",
    "BR",
    "CL",
    "CO",
    "EC",
    "FK",
    "GF",
    "GY",
    "PE",
    "PY",
    "SR",
    "UY",
    "VE",
  ],
  AF: [
    "AO",
    "BF",
    "BI",
    "BJ",
    "BW",
    "CD",
    "CF",
    "CG",
    "CI",
    "CM",
    "CV",
    "DJ",
    "DZ",
    "EG",
    "EH",
    "ER",
    "ET",
    "GA",
    "GH",
    "GM",
    "GN",
    "GQ",
    "GW",
    // British Indian Ocean Territory, in Eastern Africa by the UN geoscheme
    // that CLDR follows, though plenty of lists file it under Asia.
    "IO",
    "KE",
    "KM",
    "LR",
    "LS",
    "LY",
    "MA",
    "MG",
    "ML",
    "MR",
    "MU",
    "MW",
    "MZ",
    "NA",
    "NE",
    "NG",
    "RE",
    "RW",
    "SC",
    "SD",
    "SH",
    "SL",
    "SN",
    "SO",
    "SS",
    "ST",
    "SZ",
    "TD",
    "TG",
    "TN",
    "TZ",
    "UG",
    "YT",
    "ZA",
    "ZM",
    "ZW",
  ],
  OC: [
    "AS",
    "AU",
    "CK",
    "FJ",
    "FM",
    "GU",
    "KI",
    "MH",
    "MP",
    "NC",
    "NF",
    "NR",
    "NU",
    "NZ",
    "PF",
    "PG",
    "PN",
    "PW",
    "SB",
    "TK",
    "TO",
    "TV",
    "UM",
    "VU",
    "WF",
    "WS",
  ],
  AN: ["AQ", "BV", "GS", "HM", "TF"],
};

const CONTINENT_BY_CODE = new Map<string, ContinentCode>(
  CONTINENT_ORDER.flatMap((continent) =>
    CODES_BY_CONTINENT[continent].map(
      (code) => [code, continent] as [string, ContinentCode],
    ),
  ),
);

/**
 * `Intl.DisplayNames` is built into the browser, so the ~250 names cost nothing
 * to ship and come translated. Constructed once: it is not free to build.
 */
const regionNames = new Intl.DisplayNames(["en"], { type: "region" });

/**
 * What a country is called on screen, and what a search matches against.
 *
 * A code outside `COUNTRY_CODES` is shown as itself, deliberately, rather than
 * asked of `Intl`. CLDR answers for codes that are not countries at all — `ZZ`
 * comes back as "Unknown Region", `XA` as "Pseudo-Accents" — and a chip reading
 * "Unknown Region" next to a warning about an unrecognised code would be
 * nonsense. The bare code is both honest and the thing the user typed.
 */
export const countryLabel = (code: string): string => {
  if (!COUNTRY_CODES.includes(code as never)) return code;
  try {
    return regionNames.of(code) ?? code;
  } catch {
    // `of` throws on anything not a well-formed region code. Unreachable for a
    // generated code, kept because this must never be the thing that breaks a
    // rule editor.
    return code;
  }
};

/** Undefined for a code no continent claims — it is shown under "Other". */
export const continentOf = (code: string): ContinentCode | undefined =>
  CONTINENT_BY_CODE.get(code);

export interface CountryGroup {
  /** Heading shown above the group. */
  label: string;
  codes: string[];
}

/**
 * The picker's rows: the known countries under their continent, then anything
 * else under "Other".
 *
 * `extra` carries codes the rule already holds that `COUNTRY_CODES` does not —
 * a country added to CloudFront since the list was last generated, or a typo.
 * They are grouped, never filtered out: a save rewrites the whole rule, so a
 * code the picker does not render is a code the next save deletes.
 */
export const groupCountries = (
  extra: readonly string[] = [],
): CountryGroup[] => {
  const unclaimed = [
    ...new Set(
      [...COUNTRY_CODES, ...extra].filter((code) => !continentOf(code)),
    ),
  ].sort();

  const groups: CountryGroup[] = CONTINENT_ORDER.map((continent) => ({
    label: CONTINENT_NAMES[continent],
    codes: [...CODES_BY_CONTINENT[continent]]
      .filter((code) => COUNTRY_CODES.includes(code as never))
      .sort((a, b) => countryLabel(a).localeCompare(countryLabel(b))),
  })).filter((group) => group.codes.length > 0);

  return unclaimed.length > 0
    ? [{ label: OTHER_GROUP, codes: unclaimed }, ...groups]
    : groups;
};

/**
 * Whether the country is shown by a search for `query`, matched on the code and
 * on the name so both "FR" and "fran" find France. An empty query shows
 * everything.
 */
export const matchesCountryQuery = (code: string, query: string): boolean => {
  const needle = query.trim().toLowerCase();
  if (needle === "") return true;
  return (
    code.toLowerCase().startsWith(needle) ||
    countryLabel(code).toLowerCase().includes(needle)
  );
};

/**
 * The code a search box offers to add verbatim, or undefined.
 *
 * This is the escape hatch that keeps the list from becoming a gate: the day
 * CloudFront starts returning a code we have never generated, the user types it
 * and moves on rather than waiting for a release. Only a well-formed code
 * qualifies, since anything else would be rejected by the rule schema and
 * offering it would be a lie.
 */
export const codeFromQuery = (query: string): string | undefined => {
  const candidate = query.trim().toUpperCase();
  return /^[A-Z]{2}$/.test(candidate) ? candidate : undefined;
};
