/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/health": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Liveness probe.
     * @description Returns 200 while the API is serving. Unauthenticated.
     */
    get: operations["getHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** List all targets. */
    get: operations["listTargets"];
    put?: never;
    /** Register a new target. */
    post: operations["createTarget"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets/{id}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target id. */
        id: components["parameters"]["TargetPathId"];
      };
      cookie?: never;
    };
    /** Fetch a single target. */
    get: operations["getTarget"];
    /**
     * Update a target.
     * @description Full replace: a field omitted from the body is cleared, so send the whole target. Accepts the `id` returned by GET as long as it matches the path, so a fetched target can be edited and PUT back unchanged.
     */
    put: operations["updateTarget"];
    post?: never;
    /**
     * Remove a target from the registry.
     * @description Removes the target from the registry only — its actual DynamoDB rules table is never deleted.
     */
    delete: operations["deleteTarget"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets/{targetId}/hosts": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
      };
      cookie?: never;
    };
    /**
     * List the hosts that have rules.
     * @description Every host in the target's table holding at least one rule, sorted by host name, with a count of each rule kind.
     *
     *     A host is the DynamoDB partition key of its rules, not a stored entity of its own, so a host with no rules does not appear here — there is nothing in the table to report. Counts include disabled rules.
     *
     *     Backed by a table Scan, so cost grows with the number of rules in the target, not the number of hosts.
     */
    get: operations["listHosts"];
    put?: never;
    /**
     * Create a host that has no rules yet.
     * @description Makes a host exist before anything is stored under it, so the console can add one and still find it after a refresh. Without this a host is only the partition key of its rules, and one with none cannot be listed.
     *
     *     Writes a single marker item the edge never reads: the Lambda@Edge queries `begins_with(sk, "REDIRECT#" | "REWRITE#")`, and the marker's sort key begins with neither. It disappears with the host when the host is deleted, and is not addressable as a rule.
     *
     *     The host is stored lowercased — DNS is case-insensitive, a DynamoDB partition key is not.
     */
    post: operations["createHost"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets/{targetId}/hosts/{host}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
      };
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    /**
     * Delete a host and all of its rules.
     * @description Destructive. A host is the partition key of its rules and nothing else, so removing it means removing every redirect and rewrite stored under it. The target and its DynamoDB table are untouched.
     *
     *     A host nothing is stored under at all is a 404, not a 204 — reporting success would hide a mistyped or already-deleted host. A host that exists with no rules is not that case: it is deleted like any other, and answers 204.
     *
     *     Not atomic: the rules are removed in batches of 25, so a failure part-way leaves the host with fewer rules rather than none. Repeat the request to finish the job.
     */
    delete: operations["deleteHost"];
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets/{targetId}/hosts/{host}/rules": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
      };
      cookie?: never;
    };
    /**
     * List a host's rules by priority.
     * @description Redirect and rewrite rules for the host, in sort-key order — redirects before rewrites, ascending priority within each. That is the order the Lambda@Edge evaluates them in; the two kinds are separate lists at the edge, since redirects run at viewer-request and rewrites at origin-request. A host with no rules is an empty array, not a 404.
     */
    get: operations["listRules"];
    put?: never;
    /**
     * Create a rule for a host.
     * @description The server owns both keys: `pk` is the host from the path and `sk` is `TYPE#priority` with the priority zero-padded. Never overwrites — a priority already taken for that host and rule type is a 409.
     *
     *     The response body's `sk` is the created rule's id. It contains a `#`, so addressing the rule afterwards means percent-encoding it: `…/rules/REDIRECT%2300100`.
     *
     *     Creating a rule for a host that does not exist yet brings the host into existence, exactly as `POST /hosts` would: the host keeps its place in the list afterwards even if every rule under it is deleted, and takes an explicit `DELETE /hosts/{host}` to remove.
     */
    post: operations["createRule"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/targets/{targetId}/hosts/{host}/rules/{sk}": {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
        /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
        sk: components["parameters"]["Sk"];
      };
      cookie?: never;
    };
    /** Fetch a single rule. */
    get: operations["getRule"];
    /**
     * Replace a rule.
     * @description Full replace: a field omitted from the body is cleared, so send the whole rule — including `priority`, which is required here for the same reason.
     *
     *     Changing `priority` **moves** the rule, because the priority is part of its key: the item is rewritten under a new `sk` and removed from the old one, atomically. The rule then answers on a new URL — the response body is the authority on where it lives. Moving onto a priority another rule already holds is a 409, and neither rule is touched.
     *
     *     A body may carry `sk`, but on this route it names the rule being replaced, so it must equal the sort key in the path — not the key the new `priority` implies. A client re-prioritising a rule should simply omit it.
     */
    put: operations["putRule"];
    post?: never;
    /**
     * Delete a rule.
     * @description Deleting a rule that does not exist is a 404, not a silent 204 — the write is conditional on the item existing.
     */
    delete: operations["deleteRule"];
    options?: never;
    head?: never;
    /**
     * Enable or disable a rule.
     * @description Flips `disabled` and changes nothing else. The only edit that is not a full replace: turning a rule off is one click in the UI and must not depend on the client holding a complete, current copy of the rule.
     *
     *     Not a general PATCH — `disabled` is the only accepted field, and any other is a 400 rather than being silently ignored. A disabled rule stays in the table and keeps its priority; the Lambda@Edge skips it, which takes effect within the edge cache TTL (~1 min) rather than immediately.
     */
    patch: operations["toggleRule"];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @constant */
      status: "ok";
    };
    /** @description Fields a client supplies to create or update a target. */
    TargetInput: {
      /** @description Human-readable target name. Must contain a non-whitespace character; stored trimmed. */
      name: string;
      /** @description AWS region of the target's DynamoDB table. This pattern checks format only — the server also checks the region is one it allows, so a well-formed value can still be rejected (e.g. us-east-11). The allowed set is deployment-specific (ALLOWED_REGIONS), so it is not published here as an enum. */
      region: string;
      /** @description DynamoDB rules table the Lambda@Edge reads for this target. Checked for existence when the target is registered: a table AWS reports as absent is a 400 with a `/tableName` detail, since table names are case-sensitive and a typo would otherwise register as a second, broken target. A table the API merely cannot reach yet is accepted — IAM is granted at apply time, after registration. */
      tableName: string;
      /** @description Optional IAM role the API assumes to read and write this target's rules table. Omit to use the API's own execution role, which only reaches tables its policy already covers. Required in practice for a target registered after deploy, or one in another account. */
      roleArn?: string;
    };
    /** @description Update body. Same fields as TargetInput plus an optional `id`, which must equal the id in the path if present; a mismatch is a 400. Spelled out rather than composed with TargetInput because `allOf` cannot add a property to a schema that sets `additionalProperties: false`. */
    TargetUpdate: {
      /** @description Must equal the id in the path. Ignored otherwise. */
      id?: string;
      name: string;
      region: string;
      tableName: string;
      roleArn?: string;
    };
    /** @description A registered target. `id` is server-generated and immutable. */
    Target: {
      /** @description Server-generated id; used as the targetId in rule routes. */
      id: string;
      name: string;
      region: string;
      tableName: string;
      roleArn?: string;
    };
    /** @description A host to create, before it has any rules. */
    HostInput: {
      /** @description A hostname, not a URL — no scheme, port, path or trailing dot. This is the incoming domain rules apply to, and it becomes the DynamoDB partition key, so it is stored lowercased. */
      host: string;
    };
    /** @description One host in a target's table and how many rules of each kind it holds. Named `HostSummary` rather than `Host` because there is no fuller host resource behind it — the host is its rules. */
    HostSummary: {
      /** @description The rule host — the DynamoDB partition key. */
      host: string;
      /** @description Rules with an `sk` under `REDIRECT#`, disabled ones included. */
      redirects: number;
      /** @description Rules with an `sk` under `REWRITE#`, disabled ones included. */
      rewrites: number;
    };
    /** @description A redirect or rewrite rule item, per the shared schemas. */
    Rule:
      | components["schemas"]["redirect-rule.schema"]
      | components["schemas"]["rewrite-rule.schema"];
    /**
     * @description A rule as a client sends it: the rule's own fields plus `priority`, an integer the server zero-pads into the sort key. The response is a `Rule` — the stored item, with `pk`/`sk` and without `priority`.
     *
     *     This is the one place a rule shape is restated outside `shared/`. Draft-07 cannot relax `required` or `additionalProperties` by composition, so the input — which has no `sk` yet, and one field the item must never carry — cannot be expressed as a `$ref` to the shared schemas. Everything nested still points at them, and `openapi-rule-input.test.ts` fails if the field lists drift apart.
     */
    RuleInput:
      | components["schemas"]["RedirectRuleInput"]
      | components["schemas"]["RewriteRuleInput"];
    /** @description The enable/disable body. `disabled` is the only field this route accepts. */
    RuleToggle: {
      /** @description `true` takes the rule out of service at the edge while leaving it in the table at its current priority; `false` puts it back. */
      disabled: boolean;
    };
    /** @description Lower runs first. Zero-padded to five digits and joined to the rule type as `sk` (`REDIRECT#00100`), so it is unique per host per type — and the width is why the range ends at 99999. */
    RulePriority: number;
    /** @description Host. Derived from the path; may be sent (a rule fetched with GET carries it) but must match, or the request is a 400. */
    RuleKeyPk: string;
    /** @description Sort key. Derived by the server, and safest omitted. If sent, it must equal the key of the rule the request *addresses* — the sort key in the path on an item route, or the key derived from `type` and `priority` on create. On a PUT that changes the priority those two differ, and the path's value is the one that must be sent. */
    RuleKeySk: string;
    /** @description Redirect (erMatchRule) input. Mirrors redirect-rule.schema.json. */
    RedirectRuleInput: {
      /** @constant */
      type: "erMatchRule";
      priority: components["schemas"]["RulePriority"];
      pk?: components["schemas"]["RuleKeyPk"];
      sk?: components["schemas"]["RuleKeySk"];
      /** @enum {unknown} */
      statusCode: 301 | 302;
      redirectURL: string;
      useIncomingQueryString?: boolean;
      matches: components["schemas"]["match"][];
      disabled?: boolean;
    };
    /** @description Rewrite (frMatchRule) input. Mirrors rewrite-rule.schema.json. */
    RewriteRuleInput: {
      /** @constant */
      type: "frMatchRule";
      priority: components["schemas"]["RulePriority"];
      pk?: components["schemas"]["RuleKeyPk"];
      sk?: components["schemas"]["RuleKeySk"];
      matches: components["schemas"]["match"][];
      forwardSettings: components["schemas"]["forwardSettings"];
      disabled?: boolean;
    };
    /** @description One validation failure. Mirrors ValidationDetail in console/api/src/lib/ajv-errors.ts. */
    ValidationDetail: {
      /** @description JSON Pointer to the offending value, or "(root)" for the body itself. */
      path: string;
      /** @description Human-readable reason, straight from the schema validator. */
      message: string;
      /** @description Validator metadata identifying the field — e.g. `{"additionalProperty":"typo"}` or `{"allowedValues":[301,302]}`. The message alone often does not name the field, which is why this is passed through. Never contains request values. */
      params?: {
        [key: string]: unknown;
      };
    };
    Error: {
      error: {
        /**
         * @description Stable, machine-readable error code. Closed set — see ERROR_CODES in console/api/src/lib/errors.ts, which a test keeps in sync with this enum. UNKNOWN_TARGET and NOT_FOUND are both 404s: the first means the target id in the path is not registered, the second that the addressed resource does not exist within a known target.
         * @enum {string}
         */
        code:
          | "BAD_REQUEST"
          | "HOST_EXISTS"
          | "INTERNAL"
          | "INVALID_JSON"
          | "METHOD_NOT_ALLOWED"
          | "NOT_FOUND"
          | "RULE_EXISTS"
          | "TARGET_EXISTS"
          | "TARGET_UNREACHABLE"
          | "UNKNOWN_TARGET"
          | "VALIDATION_ERROR";
        /** @description Human-readable summary. */
        message: string;
        /** @description Optional structured detail. Present on validation failures, where each entry locates one bad field. Capped — a final entry with no `params` reports how many were omitted. */
        details?: components["schemas"]["ValidationDetail"][];
      };
    };
    match: {
      /** @enum {unknown} */
      matchType:
        "path" | "hostname" | "protocol" | "regex" | "header" | "cookie";
      /** @enum {unknown} */
      matchOperator: "equals" | "contains" | "regex";
      matchValue: string;
      negate?: boolean;
      caseSensitive?: boolean;
      /** @description Required when matchType is "header"; disallowed otherwise. */
      headerName?: string;
    };
    /** Redirect rule item (erMatchRule) */
    "redirect-rule.schema": {
      /** @description Host, e.g. www.example.com. DynamoDB partition key. */
      pk: string;
      /** @description REDIRECT#<priority>, priority zero-padded to 5 digits; lower = higher priority; unique per host per type. */
      sk: string;
      /** @constant */
      type: "erMatchRule";
      /** @enum {unknown} */
      statusCode: 301 | 302;
      redirectURL: string;
      useIncomingQueryString?: boolean;
      matches: components["schemas"]["match"][];
      disabled?: boolean;
    };
    cloudFrontHeaders: {
      [key: string]: {
        key?: string;
        value: string;
      }[];
    };
    s3Origin: {
      /** @enum {unknown} */
      authMethod: "origin-access-identity" | "none";
      customHeaders: components["schemas"]["cloudFrontHeaders"];
      domainName: string;
      path: string;
      region?: string;
    };
    customOrigin: {
      customHeaders: components["schemas"]["cloudFrontHeaders"];
      domainName: string;
      keepaliveTimeout: number;
      path: string;
      port: number;
      /** @enum {unknown} */
      protocol: "http" | "https" | "http-only" | "https-only" | "match-viewer";
      readTimeout: number;
      sslProtocols: string[];
    };
    /** Rewrite rule item (frMatchRule) */
    "rewrite-rule.schema": {
      /** @description Host, e.g. www.example.com. DynamoDB partition key. */
      pk: string;
      /** @description REWRITE#<priority>, priority zero-padded to 5 digits; lower = higher priority; unique per host per type. */
      sk: string;
      /** @constant */
      type: "frMatchRule";
      matches: components["schemas"]["match"][];
      forwardSettings:
        | {
            origin?: {
              s3?: components["schemas"]["s3Origin"];
              custom?: components["schemas"]["customOrigin"];
            } & (unknown | unknown);
            /** @description Rewritten path (and optional query string) the request is forwarded with. */
            pathAndQS?: string;
            useIncomingQueryString?: boolean;
          }
        | unknown
        | unknown;
      disabled?: boolean;
    };
    forwardSettings:
      | {
          origin?: {
            s3?: components["schemas"]["s3Origin"];
            custom?: components["schemas"]["customOrigin"];
          } & (unknown | unknown);
          /** @description Rewritten path (and optional query string) the request is forwarded with. */
          pathAndQS?: string;
          useIncomingQueryString?: boolean;
        }
      | unknown
      | unknown;
  };
  responses: {
    /** @description The request was malformed or failed schema validation. */
    BadRequest: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description That table is already registered as another target. A table is identified by (account, region, tableName) — the account coming from `roleArn`, so two accounts may register the same table name, but two roles in one account may not. */
    Conflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description Unexpected failure. The response carries only a generic message; the cause is in the function's CloudWatch logs. */
    InternalError: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The path exists but not for this method. The Lambda router owns method dispatch — API Gateway forwards every method on a `$default` route. */
    MethodNotAllowed: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description No such resource. */
    NotFound: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description The target is registered but its DynamoDB table cannot be reached — the assumed role was refused, the API's execution role does not cover the table, or the table does not exist in that region. A configuration problem, not a bad request: targets are registered at runtime while IAM is granted at apply time, and both grants are empty by default. See console/api/infra/README.md. */
    TargetUnreachable: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description That host already exists in this target — either it holds rules, or it was created empty before. Nothing was written, and no existing rule was touched. */
    HostConflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
    /** @description That priority is already taken for this host and rule type. Priority is part of a rule's key, so two rules cannot share one. Nothing was written — on a move, neither the rule being moved nor the one already there. */
    RuleConflict: {
      headers: {
        [name: string]: unknown;
      };
      content: {
        "application/json": components["schemas"]["Error"];
      };
    };
  };
  parameters: {
    /** @description Target id. */
    TargetPathId: string;
    /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
    TargetId: string;
    /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
    Host: string;
    /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
    Sk: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  getHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The API is up. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
      400: components["responses"]["BadRequest"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
    };
  };
  listTargets: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description All registered targets, sorted by name. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Target"][];
        };
      };
      400: components["responses"]["BadRequest"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
    };
  };
  createTarget: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetInput"];
      };
    };
    responses: {
      /** @description The created target. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Target"];
        };
      };
      400: components["responses"]["BadRequest"];
      405: components["responses"]["MethodNotAllowed"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalError"];
    };
  };
  getTarget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target id. */
        id: components["parameters"]["TargetPathId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The target. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Target"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
    };
  };
  updateTarget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target id. */
        id: components["parameters"]["TargetPathId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["TargetUpdate"];
      };
    };
    responses: {
      /** @description The updated target. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Target"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      409: components["responses"]["Conflict"];
      500: components["responses"]["InternalError"];
    };
  };
  deleteTarget: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target id. */
        id: components["parameters"]["TargetPathId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The target was removed from the registry. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
    };
  };
  listHosts: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The target's hosts. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HostSummary"][];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  createHost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["HostInput"];
      };
    };
    responses: {
      /** @description The created host, with both counts at zero. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["HostSummary"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      409: components["responses"]["HostConflict"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  deleteHost: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The host and all its rules were removed. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  listRules: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The host's rules. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"][];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  createRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleInput"];
      };
    };
    responses: {
      /** @description The created rule, in the shape it was stored. */
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      409: components["responses"]["RuleConflict"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  getRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
        /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
        sk: components["parameters"]["Sk"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The rule. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  putRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
        /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
        sk: components["parameters"]["Sk"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleInput"];
      };
    };
    responses: {
      /** @description The updated rule, in the shape it was stored. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      409: components["responses"]["RuleConflict"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  deleteRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
        /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
        sk: components["parameters"]["Sk"];
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The rule was deleted. */
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
  toggleRule: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        /** @description Target (DynamoDB table) id from the targets registry (ER-202). */
        targetId: components["parameters"]["TargetId"];
        /** @description Rule host — the DynamoDB partition key, e.g. www.example.com. Matched case-insensitively: the value is lowercased before it is used as a key, so `WWW.Example.com` and `www.example.com` address one host rather than two partitions. Rules are therefore always stored under the lowercased host, whichever case created them. */
        host: components["parameters"]["Host"];
        /** @description Sort key — TYPE#priority, e.g. REDIRECT#00100. */
        sk: components["parameters"]["Sk"];
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["RuleToggle"];
      };
    };
    responses: {
      /** @description The rule, as stored after the toggle. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Rule"];
        };
      };
      400: components["responses"]["BadRequest"];
      404: components["responses"]["NotFound"];
      405: components["responses"]["MethodNotAllowed"];
      500: components["responses"]["InternalError"];
      502: components["responses"]["TargetUnreachable"];
    };
  };
}
